stages:
  - build
  - test
  - sonarqube
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

sonarqube-job:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'dev'
    - if: $CI_COMMIT_BRANCH == 'main'
    - when: manual

  tags:
    - avm_groupe5
  stage: sonarqube
  image: maven:3.9.9-eclipse-temurin-22
  needs:
    - job: test-job
      artifacts: true
  allow_failure: true
  script:
    - chmod +x ./settings.sh
    - ./settings.sh
    - mvn compile -DskipTests
    - mvn sonar:sonar deploy -DskipTests 
      -Dsonar.projectKey=$PROJECT_KEY_AND_NAME
      -Dsonar.projectName=$PROJECT_KEY_AND_NAME
      -Dsonar.host.url=https://disc.univ-fcomte.fr/cr700-sonarqube
      -Dsonar.token=$SONAR_TOKEN
      -Dsonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml


build-job:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'dev'
    - if: $CI_COMMIT_BRANCH == 'main'
    - when: manual
  tags:
    - avm_groupe5
  stage: build
  image: maven:3.9.9-eclipse-temurin-22
  script:
    - mvn -B clean compile

test-job:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'dev'
    - if: $CI_COMMIT_BRANCH == 'main'
    - when: manual
  tags:
    - avm_groupe5
  stage: test
  image: maven:3.9.9-eclipse-temurin-22
  variables:
    DISPLAY: ":99"
    MAVEN_OPTS: "-Djava.awt.headless=false"
  before_script:
    # Installing dependencies for JavaFX and Xvfb
    - apt-get update -qq
    - apt-get install -y -qq xvfb libgtk-3-0 libxtst6 libxrender1 libxi6 libx11-6 libxext6 libgl1
    # Starting Xvfb (virtual X server)
    - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
    # Wait until Xfvb is ready
    - sleep 3
  script:
    - mvn -B test
  artifacts:
    when: always
    reports:
      junit:
        - "**/target/surefire-reports/TEST-*.xml"
    paths:
      - "**/target/surefire-reports/"
      - "**/target/site/jacoco/"
      - "**/target/jacoco.exec"


manual-deploy:
  stage: deploy
  tags:
    - avm_groupe5
  when: manual
  only:
    - main
  needs:
    - sonarqube-job
  script:
    - chmod +x ./settings.sh
    - ./settings.sh
    - echo "Starting manual Maven deploy..."
    - mvn deploy -s ~/.m2/settings.xml
  environment:
    name: production
