stages:
  - build
  - test
  - sonarqube

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository


sonarqube-job:
  rules:
    - if: $CI_COMMIT_BRANCH == 'dev'
    - if: $CI_COMMIT_BRANCH == 'main'

  tags:
    - avm_groupe5
  stage: sonarqube
  image: maven:3.9.9-eclipse-temurin-22
  script:
    - chmod +x ./settings.sh
    - ./settings.sh
    - mvn clean jacoco:prepare-agent test jacoco:report install sonar:sonar deploy
      -Dsonar.projectKey=$PROJECT_KEY_AND_NAME
      -Dsonar.projectName=$PROJECT_KEY_AND_NAME
      -Dsonar.host.url=https://disc.univ-fcomte.fr/cr700-sonarqube
      -Dsonar.token=$SONAR_TOKEN

build-job:
  tags:
    - avm_groupe5
  stage: build
  image: maven:3.9.9-eclipse-temurin-22
  script:
    - mvn -B clean compile

test-job:
  tags:
    - avm_groupe5
  stage: test
  image: maven:3.9.9-eclipse-temurin-22
  script:
    - mvn -B test

